# Generated by Django 2.2.7 on 2020-01-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNumber', models.IntegerField()),
                ('CName', models.CharField(max_length=100)),
                ('CFaculty', models.CharField(max_length=100)),
                ('CDuration', models.CharField(max_length=100)),
                ('CFees', models.IntegerField()),
                ('CContent', models.CharField(max_length=100)),
            ],
        ),
    ]
