# Generated by Django 2.2.7 on 2020-01-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durgasoftapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
