# Generated by Django 2.2.7 on 2020-01-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durgasoftapp', '0002_contactdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
