# Generated by Django 2.2.7 on 2020-01-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durgasoftapp', '0003_auto_20200104_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
